services:
  discord-ser:
    image: discord-bot-img
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - type: bind
        source: .
        target: /usr/clarence/
      - /usr/clarence/node_modules
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONGOOSE=${MONGOOSE}
      - PREFIX='-'
    ports:
      - 6002:6002
    container_name: discord-cont
  mongo-ser:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    container_name: mongo-discord-cont
